Test motivation
sw8f17/paper pull request #10
Opened 2017-02-20 14:21 UTC by VirtualSatai

2017-02-20 21:42 UTC, ThomasPilgaard requested changes

2017-02-20 21:42 UTC, ThomasPilgaard commented on cha/sota/test/whywetest.tex
> +That is we want to identify some parameters, and test to what degree the state of art achieves them.
Jeg synes det er en lidt sjov indledning på linje 1 og 2. Måske starte med at der var fundet nogle apps i SOTA, og at vi gerne vil se om de opfylder den initerende problemstilling. Det er også lidt i den retning det står, men det er lidt svært at gennemskue.

2017-02-21 08:49 UTC, ThomasPilgaard approved these changes

2017-02-21 12:32 UTC, DelusionalLogic approved these changes

2017-02-21 12:32 UTC, DelusionalLogic commented on cha/sota/test/whywetest.tex
> +        \item If the song changes are the synchronization preserved?
If the song changes is the synchronization preserved?

2017-02-21 12:36 UTC, merged