Test: discussion + conclusion
sw8f17/paper pull request #15
Opened 2017-02-23 12:14 UTC by VirtualSatai

2017-02-23 12:24 UTC, ThomasPilgaard requested changes

2017-02-23 12:24 UTC, ThomasPilgaard commented on cha/sota/test/conclusion.tex
> +    Yet to test formally, but we expect AmpMe to be better than SoundSeeder, but none of them to be acceptable.
Mangler der ikke en forklaring på "Drift" i samme stil som de andre?

2017-02-23 12:24 UTC, ThomasPilgaard commented on cha/sota/test/conclusion.tex
> +    I find the following pretty poor, any suggestions for improvement would be appreciated.
Måske fokuser på at SoundSeeder og AmpMe ikke opfylder den initerende problemformulering, for så ligger det rigtig godt op til den rigtige problemformulering.

2017-02-23 13:13 UTC, TriXXeD approved these changes

2017-02-23 13:13 UTC, TriXXeD commented on cha/sota/test/conclusion.tex
> +In the tests we have tested the questions we posed for the apps in \vref{sec:sota_test}.
How do you test a question?

2017-02-24 11:08 UTC, VirtualSatai commented on cha/sota/test/conclusion.tex
> +In the tests we have tested the questions we posed for the apps in \vref{sec:sota_test}.
Har prøvet at omformulere :)

2017-02-24 11:28 UTC, ThomasPilgaard approved these changes

2017-02-24 12:01 UTC, merged