First draft on vol and area use case category
sw8f17/paper pull request #16
Opened 2017-02-24 12:04 UTC by ThomasPilgaard

Read for contextual stuff.

2017-02-24 12:52 UTC, VirtualSatai requested changes

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +Some of the aspects of the use cases occur in several of them, for instance the requirement of precise synchronization.
Sætningen er lidt uklar. Hvad betyder "them"? Overvej omformulering

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +Examples of use cases in this category could be the following:
Det er en meget svag formulering imo.

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +    \item[Social gathering/Party] \hfill\\
Vælg en af de 2 som overskrift

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        With synchronization of the music, the participants can use their phone and play the same music as one big speaker.
Lav sætningen om til noget i retningen af:
"Given the ability to play music synchronized accross all their smarthphones [...]"

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        making it more quieter for them while the other participants still can hear the music.
"more quieter" much wow

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        the synchronization have to be precise enough so that there is no difference in playback of the music between the devices.
Evt:

"[...] no difference [...]" -> "[...] no perceived difference [...]"

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        At a music festival, there is often an area for the concerts and an area for people to sleep, often called a camp.
Don't call it the sleeping area.

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        By having these phones connect to a device, which can send synchronized music to the phones,
Omformuler her, da det introducere en arbitrær restiktion.

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        the festival participants should be able to control the volume locally without affecting the rest.
Yderligere kunne alle anmode om sange til playlisten, her og til party.

2017-02-24 12:52 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +        In the case that they live in a big apartment or house, they can only hear the music in one room,
Jeg tror det ville være bedre at frame det som en drøm:
"What if the music playback would be synchronous across all rooms of the home?" 

Eller sådan noget

2017-02-27 09:39 UTC, VirtualSatai requested changes

2017-02-27 09:39 UTC, VirtualSatai commented on cha/usecase/vol_area.tex
> +\end{description}
En lille opsumering herunder kunne være dank.

2017-02-27 10:17 UTC, VirtualSatai approved these changes

2017-02-27 12:12 UTC, mathiassmichno approved these changes

2017-02-27 12:26 UTC, merged