Procedure work:open_hands:
sw8f17/paper pull request #19
Opened 2017-02-27 13:04 UTC by DelusionalLogic

2017-02-27 13:29 UTC, ThomasPilgaard requested changes

2017-02-27 13:29 UTC, ThomasPilgaard commented on cha/sota/test/procedure.tex
> +first aspect we wanted to test was offset between playing devices.
Jeg synes at alle fire forskellige aspekter skal nævnes her, som en form for indledning til subsektionen.

2017-02-27 13:29 UTC, ThomasPilgaard commented on cha/sota/test/procedure.tex
> +measurements are correlated using the FFT method also described in
evt. AC på FFT.

2017-02-27 13:29 UTC, ThomasPilgaard commented on cha/sota/test/procedure.tex
> +For AmpMe switching songs can be triggered by clicking the previous song
Er det ikke nærmere at starte sangen forfra i stedet for "switching songs"?

2017-02-27 13:29 UTC, ThomasPilgaard commented on cha/sota/test/procedure.tex
> +tests, a script is written to handle the testing part. The test is
Disse scripts i bilag og en ref her?

2017-02-27 14:21 UTC, DelusionalLogic commented on cha/sota/test/procedure.tex
> +first aspect we wanted to test was offset between playing devices.
Det er allerede nævnt 2 subsections tilbage

2017-02-27 14:21 UTC, DelusionalLogic commented on cha/sota/test/procedure.tex
> +For AmpMe switching songs can be triggered by clicking the previous song
Switching songs er en reference til en tidligere section

2017-02-27 14:21 UTC, DelusionalLogic commented on cha/sota/test/procedure.tex
> +tests, a script is written to handle the testing part. The test is
Der er en ref i det tidligere kapitel

2017-02-28 11:52 UTC, VirtualSatai requested changes
Jeg syntes ikke dette er den bedste måde at repræsenere det vi prøver at sige med sectionen. De er også ikke særlig god sammenhæng mellem dette og tidligere. Jeg ville fortrække at om hver test vi lavede stod der:
 - Hvilket spørgsmål svarer denne test til?
 - Hvilke skridt skete? gerne på punktform.
 - Hvilken form havde målingerne?

2017-02-28 11:52 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +\cref{subsec:test_setup}.
Du beskriver ikke hvad der sker mellem målingerne. Der skal også være en reference herfra -> resultat eller tilbage derfra. Hvilket spørgsmål fra starten svarer denne test på?

2017-02-28 11:52 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +slider one step for every iteration. It starts off moving right, until
iteration of what?

2017-02-28 11:52 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +slider one step for every iteration. It starts off moving right, until
moving right? Hvad betyder det?

2017-02-28 11:52 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +slider one step for every iteration. It starts off moving right, until
Du kan refere tilbage til det billede i sota af slideren.

2017-02-28 11:52 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +script takes 5 samples and then switches songs. It does this 5 times.
Du skriver samples her? Hvad er det? Og hvorfor er det forskelligt fra ordet "measurements" du bruger tidligere?

2017-02-28 11:53 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +\subsection{Procedure}\label{subsec:procedure}
Overskriften prodecure siger ikke meget, måske "Test Procedure" ?

2017-02-28 12:58 UTC, DelusionalLogic commented on cha/sota/test/procedure.tex
> +\cref{subsec:test_setup}.
Det er fordi der ikke sker noget her imellem testene

2017-02-28 13:16 UTC, VirtualSatai requested changes

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
Meta tekst, hvad indeholder denne section?

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +want the apps to change song, possibly causing a resync, while testing.
we looped part of the middle of the song ...

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +``speakers''. The ``speakers'' are the ones connected to the computer,
Bare for at være eksplicit, så skriv at de er connected med det kabel vi beskrev tidligere.

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +fulfilled that requirement by having the master serve a wifi hotspot,
"wifi hotspot" kalder vi tidliger ad-hoc network og Android Hotspot. Kan vi blive enige om et begreb?

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +5 sample, each of which are the median of 5 10-second measurements. The
Tal under 10 skriv som ord :)

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
>  \paragraph{Offset}
Der er noget rod i heirakiet af overskrifter her.

2017-02-28 13:16 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +then moves back to the initial position and repeats for the negative
ref til billedet af sliders

2017-03-02 08:39 UTC, VirtualSatai requested changes

2017-03-02 08:39 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
> +\subsection{Individual test procedure}
Alt over det her er i princippet setup og ikke prodecure, skal vi ikke flytte det?

2017-03-02 08:39 UTC, VirtualSatai commented on cha/sota/test/procedure.tex
Omkring drift, så kan vi jo per def ikke bruge den sang vi har lavet tidligere ...

2017-03-02 09:19 UTC, DelusionalLogic commented on cha/sota/test/procedure.tex
Hvad ville du skrive? Jeg ved ikke helt hvad jeg skal gøre ved det.

2017-03-02 09:44 UTC, ThomasPilgaard approved these changes

2017-03-02 11:19 UTC, VirtualSatai approved these changes

2017-03-02 11:28 UTC, merged