A few of my suggested changes
sw8f17/paper pull request #28
Opened 2017-03-03 12:28 UTC by DelusionalLogic

2017-03-06 09:05 UTC, VirtualSatai requested changes
Der er et par ting som ikke er bleven forbedret af det her. Men de fleste er god.

2017-03-06 09:05 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +To clarify, Google Play Store and the App Store are the official places to install or buy apps for Android and iOS devices respectively.
What does this clarify?

2017-03-06 09:05 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +To connect to a playing master device, as a slave.
Det her kan ikke stå alene, hvis du laver punktummet om til et kolon så kan den gå.

2017-03-06 09:05 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +Which mean WiFi or a mobile hotspot is required.
Der står "ad--hoc network (Android Hotspot)" tidligere i afsnittet, lav dem alle sammen om til at være det samme.

2017-03-06 15:03 UTC, TriXXeD requested changes

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +The current version as of writing is 1.6.5.
Har du tænkt dig at tjekke om dette er korrekt inden i aflevere? for ellers virker det andet bedre

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +To connect to a playing master device, as a slave.
+1

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +which means that all phones have to be on the same network\cite{soundseether_faq}\jjnote{Der mangler måske noget her med NAT}, it is also possible to use an ad--hoc network (Android Hotspot).
Sota Apps er slet ikke teknisk nok til at drage NAT ind imo

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +The current version of the app at the time of writing is 5.1.1.
Same as before

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +If a party is found nearby, you can join it as a slave and play the master's music.
Er der en range limit på hvornår man kan join et fundet netværk?

2017-03-06 15:03 UTC, TriXXeD commented on cha/sota/sota_app.tex
> +The design is very minimalistic, and seems to follow the new ``Material Design'' guidelines set out by Google.
Virker underligt at refere til en eller anden guideline som vi formegentlig aldrig kommer til at bruge igen uden at forklare hvad det betyder.

2017-03-06 15:50 UTC, mathiassmichno commented on cha/sota/sota_app.tex
> +The design is very minimalistic, and seems to follow the new ``Material Design'' guidelines set out by Google.
om ikke andet, så skal der en fodnote på Material design

2017-03-06 15:57 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +To clarify, Google Play Store and the App Store are the official places to install or buy apps for Android and iOS devices respectively.
Pas, jeg har ikke skrevet det.

Jeg vil gætte på at det er hvor de er fundet, altså kapitlet over

2017-03-06 15:58 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +Which mean WiFi or a mobile hotspot is required.
Jeg kan nu godt lide diversiteten af det som skrevet

2017-03-06 15:59 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +The current version as of writing is 1.6.5.
Det andet er ikke en god sætning overhovedet, men det kan være at det rigtige ville være at indsætte datoen!

2017-03-06 16:01 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +which means that all phones have to be on the same network\cite{soundseether_faq}\jjnote{Der mangler måske noget her med NAT}, it is also possible to use an ad--hoc network (Android Hotspot).
Jeg mener heller ikke en detaljeret og nuanceret beskrivelse af hvad NAT er, men bare at der måske skal stå at det at være på det samme netværk ikke nødvendigvis er nok. Det er kun vigtigt hvis det bliver brugt senere.

2017-03-06 16:01 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +The current version of the app at the time of writing is 5.1.1.
Same as before

2017-03-06 16:02 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +If a party is found nearby, you can join it as a slave and play the master's music.
Det er er AmpMe, som ikke kræver lokalt netværk. Den operere udelukkende på hvem er i nærheden af dig med GPS.

2017-03-06 16:05 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +The design is very minimalistic, and seems to follow the new ``Material Design'' guidelines set out by Google.
Jeg mener det som en observation. Hvis vi skal bruge det senere kan vi referere tilbage til det.

2017-03-06 19:55 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +To clarify, Google Play Store and the App Store are the official places to install or buy apps for Android and iOS devices respectively.
Nej, men du har fjernet det de clarifier, da der ikke længere står noget om "Google Play Store and App Store".

2017-03-07 07:27 UTC, DelusionalLogic commented on cha/sota/sota_app.tex
> +To clarify, Google Play Store and the App Store are the official places to install or buy apps for Android and iOS devices respectively.
Linje 11 snakker stadig om play/app store. Det er min opfattelse at det er der den her clarify referere til.

2017-03-07 12:15 UTC, VirtualSatai approved these changes

2017-03-07 12:16 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +Which mean WiFi or a mobile hotspot is required.
God ide, lad os være inconsistent ... sounds like a plan

2017-03-07 12:17 UTC, TriXXeD approved these changes
Sæt en dato ind hvor der skrives versionnumre så vi kan garantere korrektheden senere

2017-03-07 12:43 UTC, merged