Problem statement Sass
sw8f17/paper pull request #30
Opened 2017-03-05 15:41 UTC by mathiassmichno

plz ignore until next sprint

2017-03-05 17:42 UTC, DelusionalLogic commented
Test post please ignore

2017-03-06 14:27 UTC, TriXXeD requested changes
Lav din \cnameref om således at den sætter navnet på kapitlet i en inskudt sætning, Derudover pensl termer ud, står også i en fxnote

2017-03-06 15:22 UTC, mathiassmichno commented
cnameref skal redefineres i master ikke her.

2017-03-07 12:19 UTC, TriXXeD approved these changes

2017-03-07 12:37 UTC, merged