Draft on requirements elicitation
sw8f17/paper pull request #38
Opened 2017-03-15 12:48 UTC by ThomasPilgaard

2017-03-15 13:24 UTC, VirtualSatai submitted a review, later dismissed

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +To do requirement elicitation, we focus on the requirements posed in \cref{part:introduction}.
wut

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +        The master is in control of the created session, including the playback of the media.
"including the playback of the media" hvad menes der? at være højtaler, alle skal ved gøre det?

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +        A user must be able to mute the playback when it is connected to a session, which relates to the use cases found in \cref{sec:category_increase_volume_and_area}.
bare lige for at gøre det klart kunne man skrive at denne er relateret til den forrige.

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +            $x$ is the maximum desynchronization that will not be noticed by a listener.
Vi skal finde det her tal.

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +        Then the user can see what song is playing and how much is left of the song.
clearify the second sentence (all users should be included)

2017-03-15 13:24 UTC, VirtualSatai commented on cha/req.tex
> +        have a repeat button to repeat a specific media and be able to queue media selected by the users.
both master and slave

2017-03-15 13:29 UTC, DelusionalLogic submitted a review, later dismissed

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        This means that the app have to run on Android five and later versions.
Has

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +    \item \textbf{Run on Android 5.0+} \hfill\\
Should be something like:

The Android sound stack underwent significant design changes in version 5.0. We determine those changes might be important for our design and implementation.

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        As mentioned in the problem statement in \cref{cha:problem_statement}, Android is chosen since it is the available system in our project group.
Sounds silly.

If it says so in the other place, why here too?

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        To be able to achieve multiple playback across multiple devices, as mentioned in \cref{cha:problem_statement},
What is "multiple playback"?

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        To be able to achieve multiple playback across multiple devices, as mentioned in \cref{cha:problem_statement},
In vs on til cref

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        then two or more devices have to be able to connect to each other wirelessly.
What how? Der står wirelessly i titlen, men det er vel ikke et krav at de skal være wireless fordi de skal være multiple?

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        This session makes it possible to transmit data from the master to the connected slaves.
huh?

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        then a user must be able to control and change the volume his device when it is connected to a session.
of his

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        If the user do not want to listen to the music as loud as the rest connected to the session, as mentioned in \cref{sec:category_increase_volume_and_area},
user does

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        As mentioned in the problem statement in \cref{cha:problem_statement}, the app must be able to manipulate the playback of the audio.
Manipulate how?

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        so the device play in sync with the rest of the connected devices in the session.
plays

2017-03-15 13:29 UTC, DelusionalLogic commented on cha/req.tex
> +        When users use the app in according to the use cases mentioned in \cref{sec:category_increase_volume_and_area},
too much use

2017-03-21 10:16 UTC, VirtualSatai requested changes

2017-03-21 10:16 UTC, VirtualSatai commented on cha/req.tex
> +    \item\label{req:manipulate} \textbf{Manipulate playback on all devices in a session.} \hfill\\
Jeg syntes ikke dette krav er så god som en overskrift. Det er som om der mangler noget.

2017-03-21 10:16 UTC, VirtualSatai commented on cha/req.tex
> +    \item\label{req:manipulate} \textbf{Manipulate playback on all devices in a session.} \hfill\\
På linje med det, skal der nok også lidt mere beskrivelse til, altså at vi snakker om offset osv.

2017-03-21 12:16 UTC, VirtualSatai requested changes
"application" -> "app" please.
Nej

2017-03-21 12:16 UTC, VirtualSatai commented on cha/req.tex
> +    \item\label{req:manipulate} \textbf{For all devices in a session it should be possible to manipulate the playback on each individual device.} \hfill\\
"It should be possible to manipulate the playback on each device separately"
Måske?

2017-03-22 13:44 UTC, VirtualSatai approved these changes

2017-03-22 13:45 UTC, merged