Rdy4FirstReview
sw8f17/paper pull request #41
Opened 2017-03-27 13:01 UTC by TriXXeD

2017-03-27 13:32 UTC, ThomasPilgaard requested changes

2017-03-27 13:32 UTC, ThomasPilgaard commented on cha/external_architecture.tex
> +External architecture refers to the architecture between devices, i.e. the way in which they communicate and are structured.
"are structured" henleder vel stadig på "devices". Menes der ikke hvordan kommunikationen er "structured"?

2017-03-27 13:32 UTC, ThomasPilgaard commented on cha/external_architecture.tex
> +We consider three different external architectures, before deciding upon the one we deem the best fit.
Imo kan jeg godt li' at disse tre bliver nævnt.

2017-03-27 13:32 UTC, ThomasPilgaard commented on cha/external_architecture.tex
> +The solution also relies on an internet connection being available and is affected by bandwidth, furthermore a server needs to be available, in the case of widespread use we would need enough hardwar
imo "The solution" -> "This solution"

2017-03-27 13:32 UTC, ThomasPilgaard commented on cha/external_architecture.tex
> +With all devices being equal it also means having to reach consensus to make decisions, simple decisions like playback control could be managed through a majority voting system, but the more complex
dunno about "is infinitely more complex".

2017-03-27 13:32 UTC, ThomasPilgaard commented on cha/external_architecture.tex
> +Ultimately the key challenge is synchronizing the clocks, and to utilize a synchronized network even a few milliseconds matter; as such we are not interested in a Peer--To--Peer network as synchroniz
Synes at "synchronizing the clocks" kommer lidt pludselig her som et stort problem. Det er ikke nævnt under Local Centralized, og i Remote Centralized er det mere som noget der kan gøres med serveren, det er kun ved P2P, men det er mere som P2P der gør det svært. Måske lidt mere fokus i de tre sync metoder at sync af clocks er et problem, så bliver det nemmere at retfærdiggøre senere hvorfor vi bruger energi på det.

2017-03-28 08:13 UTC, TriXXeD commented on cha/external_architecture.tex
> +External architecture refers to the architecture between devices, i.e. the way in which they communicate and are structured.
Det hendleder stadig til devices, det er eksempelvis om der er et hierarki eller om alle devices er lige etc.

2017-03-28 10:28 UTC, ThomasPilgaard approved these changes

2017-03-28 10:40 UTC, mathiassmichno approved these changes

2017-03-28 10:43 UTC, merged