Feature core idea
sw8f17/paper pull request #54
Opened 2017-05-08 10:26 UTC by VirtualSatai

2017-05-08 12:34 UTC, mathiassmichno commented
vi kan godt uddybe lidt, det er trods alt "core idea", det virker mere som "core issues".
Måske brug mere tid på at snakke om hvorfor, og ikke hvad der står i vejen.

2017-05-08 12:34 UTC, mathiassmichno requested changes
vi kan godt uddybe lidt, det er trods alt "core idea", det virker mere som "core issues".
Måske brug mere tid på at snakke om hvorfor, og ikke hvad der står i vejen.

2017-05-09 07:37 UTC, TriXXeD approved these changes

2017-05-09 07:51 UTC, mathiassmichno approved these changes

2017-05-09 07:53 UTC, merged