Connecting devices!!!
sw8f17/paper pull request #61
Opened 2017-05-18 09:30 UTC by VirtualSatai

2017-05-18 11:57 UTC, TriXXeD requested changes

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +This would then become a problem, when one started a new session using the same devices as a previous one, but with a different master.
why?

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +In addition to the server creating a new group, once it starts broadcasting its service.
This sentence makes no sense, in addition to the server creating a new group it does what when it starts broadcasting?

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +This becomes a problem, when a new session using the same devices as a previous one, but with a different master is started.
why?

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +To explain how this occurs we have constructed an slightly simplified UML sequence diagram, on \cref{fig:seq_server_client}.
this = ?

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +After accepting them it creates a MessageConnection, which is our abstraction, which is run on a separate thread for each connection from the server to the client, and vice versa.
Our abstraction of what?

2017-05-18 11:57 UTC, TriXXeD commented on cha/implementaion/multidevice/our_communication.tex
> +\begin{description}
It is mentioned that we send timestamps in regards to when to play something, but it is never mentioned how a client knows what offset they have to apply, nor where we explain this

2017-05-18 12:17 UTC, VirtualSatai commented on cha/implementaion/multidevice/our_communication.tex
> +\begin{description}
På nuværende tidspunkt er der ikke noget som hedder offsets. Det bliver først introduceret i et senere afsnit (det næste).

2017-05-19 09:12 UTC, ThomasPilgaard requested changes

2017-05-19 09:12 UTC, ThomasPilgaard commented on cha/implementaion/multidevice/our_communication.tex
> +We experienced several issues implementing Service Discovery in our app, the most notable being group negotiation.
Jeg synes godt der kan være en forklaring på hvad en WiFi Direct group er og helt eksplicit hvordan vores sessions hænger sammen med WiFi Direct groups. Så vil det problem med de samme devices men forskellig master også være mere indlysende.

2017-05-19 09:12 UTC, ThomasPilgaard commented on cha/implementaion/multidevice/our_communication.tex
> +To explain how the service discovery occurs we have constructed an slightly simplified UML sequence diagram, on \cref{fig:seq_server_client}.
IMO, så synes jeg at figuren skal komme helt til sidst, når alt i figuren har være forklaret, og så synes jeg at den skal gås igennem.

2017-05-19 09:12 UTC, ThomasPilgaard commented on cha/implementaion/multidevice/our_communication.tex
> +After accepting a connection it creates a MessageConnection, which is our abstraction, which is run on a separate thread for each connection from the server to the client, and vice versa.
MessageConnection i \code?
"which is our abstraction" of what?
(double which)
Forklar her helt præcist hvad en "message" er, så bliver "Sending the Messages" sektionen mere indlysende.

2017-05-19 09:13 UTC, ThomasPilgaard requested changes

2017-05-19 09:13 UTC, ThomasPilgaard commented on cha/implementaion/multidevice/our_communication.tex
> +This is shown in \cref{fig:message_layout}.
Jeg forstår ikke helt sammenhængen mellem figuren og teksten.

2017-05-22 07:45 UTC, TriXXeD approved these changes

2017-05-22 07:47 UTC, ThomasPilgaard approved these changes
seems good.jpg

2017-05-22 07:47 UTC, merged