moved some information from conclusion to sync as i need it for the c…
sw8f17/paper pull request #65
Opened 2017-05-22 13:31 UTC by TriXXeD

…onclusion

2017-05-23 08:57 UTC, VirtualSatai requested changes

2017-05-23 08:57 UTC, VirtualSatai commented on cha/design/sync.tex
> +\section{Refining the Synchronization Method --- SNTP}
"Refining" er lidt underligt imo, det er jo nærmere en indsnævring end en raffinering ?

2017-05-23 08:57 UTC, VirtualSatai commented on cha/design/sync.tex
> +\ac{SNTP} was developed as an \ac{NTP} alternative for small computers and micro-controllers, which happens to fit the description of smartphones.
Lidt en bold claim, når ens telefon har 6 kerner, og basicly en GPU.

2017-05-23 08:57 UTC, VirtualSatai commented on cha/design/sync.tex
> +\ac{SNTP} was developed as an \ac{NTP} alternative for small computers and micro-controllers, which happens to fit the description of smartphones.
(og masser af memory)

2017-05-23 08:57 UTC, VirtualSatai commented on cha/design/sync.tex
> +    As mentioned before, in order to adjust the clock through the application the device must be rooted, since we do not want to impose this requirement onto users, drift alleviation would be nullifi
Jeg forstår ikke hvorfor dette er relavant, uanset hvilken løsning vi vælger så kan vi ikke ændre på uret på android telefonen (heller ikke sntp)

2017-05-23 08:57 UTC, VirtualSatai commented on cha/design/sync.tex
> +    However once again, this would require a rooted device and as such is irrelevant for our case.
igen ...

2017-05-24 07:29 UTC, TriXXeD commented on cha/design/sync.tex
> +\section{Refining the Synchronization Method --- SNTP}
"make minor changes so as to improve or clarify (a theory or method)." - vil nu mene Refining passer meget godt på hvad der sker i denne section

2017-05-24 07:30 UTC, TriXXeD commented on cha/design/sync.tex
> +\ac{SNTP} was developed as an \ac{NTP} alternative for small computers and micro-controllers, which happens to fit the description of smartphones.
Synes ikke der er noget bold I at kalde en smartphone en "small computer", tværtimod synes jeg da det er rimelig spot on, den er trods alt væsentlig mindre end en bærbar/stationær

2017-05-24 07:34 UTC, TriXXeD commented on cha/design/sync.tex
> +    As mentioned before, in order to adjust the clock through the application the device must be rooted, since we do not want to impose this requirement onto users, drift alleviation would be nullifi
Det er jo lige netop hele pointen, det er en begrundelse for hvorfor vi vil bruge SNTP istedet, eftersom nogle af de fordele som NTP har, ikke kan benyttes

2017-05-24 07:34 UTC, TriXXeD commented on cha/design/sync.tex
> +    However once again, this would require a rooted device and as such is irrelevant for our case.
As before

2017-05-24 08:56 UTC, VirtualSatai commented
We could make a pros/cons table maybe? :D

2017-05-24 09:43 UTC, ThomasPilgaard requested changes
Made a single comment in the text.

2017-05-24 14:21 UTC, ThomasPilgaard approved these changes

2017-05-24 14:23 UTC, VirtualSatai approved these changes

2017-05-24 14:29 UTC, merged