Draft on SOTA apps
sw8f17/paper pull request #7
Opened 2017-02-15 14:58 UTC by ThomasPilgaard

A draft on SOTA apps.
Read for that it makes sence and minor mistakes.

2017-02-16 10:03 UTC, TriXXeD commented on cha/introduction/sota_app.tex
> +This can be an annoyance in the case where there is no WiFi available and all devices have to be on the same access point.
Dette er forvirrende - hvilken en af de to er en annoyance? SoundSeeder virker da superier her eftersom du kan lave et ad-hoc network men du nævner det er en annoyance at alle skal være på samme AP, så hvad refere "this" til?

2017-02-16 10:07 UTC, TriXXeD requested changes

2017-02-16 10:07 UTC, TriXXeD commented on cha/introduction/sota_app.tex
> +\subsection{Determining the State of the Art}
Savner generelt en vinkel som er brugbar for os. Der er fokus på user experience hvilket vi ikke rigtig kan bruge til noget i vores project, dette gælder også de enkelte paragrapher der er rundt omkring omkring minimalistisk og simplistisk design. - Conclusionen virker for mig som et app-review du finder på buzzfeed for at finde ud af hvilken app du skal vælge, from for at udmunde i noget som vi kan gå videre med i vores project

2017-02-16 10:07 UTC, TriXXeD commented on cha/introduction/sota_app.tex
> +This can be an annoyance in the case where there is no WiFi available and all devices have to be on the same access point.
Dette er forvirrende - hvilken en af de to er en annoyance? SoundSeeder virker da superier her eftersom du kan lave et ad-hoc network men du nævner det er en annoyance at alle skal være på samme AP, så hvad refere "this" til?

2017-02-16 10:10 UTC, TriXXeD commented on cha/introduction/sota_app.tex
> +\subsection{Determining the State of the Art}
For clarification:
Synes det burde være mere analyse, mindre review - ved godt det er seperat fra tests men synes stadig der burde være value i afsnittet, et eksempel ville være at overveje hvorfor har alle en manual synch feature, hvordan affecter det vores sync, bruger de mic til at autosynch? hvordan virker deres autosynch features hvis du kan finde noget om det - mere dybdegående information kan godt findes uden test

2017-02-19 00:07 UTC, DelusionalLogic commented on cha/introduction/sota_app.tex
> +This can be an annoyance in the case where there is no WiFi available and all devices have to be on the same access point.
Jeg er stort set enig. Jeg tror det er en reference til at ampme kan bruges over internettet, altså 3g og nattet fra hindanden. Men jeg er enig i at det ikke fremgår klart nok.

2017-02-20 13:25 UTC, TriXXeD approved these changes

2017-02-20 13:55 UTC, VirtualSatai requested changes

2017-02-20 13:55 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +    \caption{Comparison between the apps.}\label{tab:sota_comp}
As of when?

2017-02-20 13:55 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +The second app is AmpMe\footnote{http://www.ampme.com}, made by Amp Me Inc.
What version of the app is tested?

2017-02-20 13:55 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +Therefore to be a part of the state of the art, an app have to be able to both automatically and manually synchronize.
Tilføj en segway til test

2017-02-20 13:55 UTC, VirtualSatai commented on cha/sota/sota_app.tex
> +The third app, Chorus, does not support other devices than Android, narrowing down the supported devices compared to SoundSeeder and AmpMe.
flyt dette øverst, så det passer bedre med segway til test

2017-02-20 14:23 UTC, VirtualSatai approved these changes

2017-02-20 14:26 UTC, merged